### PR TITLE
[API] Admin create new category 

### PR DESCRIPTION
**Pull request by KristianGombosh**

### CODE REVIEW

**Comment by TomashGombosh** [comment]
@KristianGombosh could we change the request to add an only category?
 I will change the requirements.
 
 I think adding subcategory will be as separate task.

**Comment by KristianGombosh** [comment]
> @KristianGombosh could we change the request to add an only category? I will change the requirements.
> 
> I think adding a subcategory will be a separate task.

Subcategory required when we get all categories so adding category without subcategory will cause an issue for get all category request
image

image

**Comment by TomashGombosh** [comment]
@KristianGombosh you are correct. 
Could you add an //TODO to this, and open a new issue to refactor and remove that dependency? 

Because It breaks a single responsibility principle.

After you create an issue, I will merge your PR.

**Comment by KristianGombosh** [comment]
> @KristianGombosh you are correct. Could you add an //TODO to this, and open a new issue to refactor and remove that dependency?
> 
> Because It breaks a single responsibility principle.
> 
> After you create an issue, I will merge your PR.

https://github.com/afj-solution/buy-it-api/issues/63

**Review by TomashGombosh — APPROVED** [review]

**Pull request merged**
